### ISSUE TITLE
files downloaded from p2pchat cant be opened

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#18]

**Comment by tatssato** [comment]
1. alice send bob an image or file.
2. bob tries to download it
3. opens the downloaded file
4. fails to open

**Comment by mechanicko** [comment]
Added access to p2p file bytes in components. 
For now, author can download file after being sent.
Still needs the getFileBytes method to be integrated so the file bytes can be fetched from the HC and added to the redux state.

**Comment by mechanicko** [comment]
I tried passing a callback function to the fileview component that triggers the getFileBytes for p2p files so that we only need to download the file bytes when we actually open a file. Displaying the file in the chat box can just use the thumbnail bytes.

@nkgardose is this an efficient way of going doing this?

**Comment by mechanicko** [comment]
fixed in 169ffaaae117b79064b3698dabd8a295027de2ee
